name: Pack addon

on:
  workflow_dispatch:

jobs:
  pack:
    name: Pack addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare addon
        shell: bash
        run: |
          ADDON_NAME='splasher'
          ADDON_FOLDER='${{ github.workspace }}/addons/$ADDON_NAME/'
          cp --no-clobber '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' '$ADDON_FOLDER'
      - name: Pack files into a .zip
        shell: bash
        run: |
          ADDON_NAME='splasher'
          ADDON_ZIP='$ADDON_NAME.zip'
          ADDON_FOLDER='${{ github.workspace }}/addons/$ADDON_NAME/'
          zip -r '$ADDON_ZIP' '$ADDON_FOLDER'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "splasher"
          path: |
            ${{ github.workspace }}/splasher.zip
          retention-days: 30
