name: Pack addon

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  pack:
    name: Pack addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare addon
        shell: bash
        run: |
          ADDON_NAME='romgerman.splasher'
          ADDON_FOLDER="${{ github.workspace }}/addons/${ADDON_NAME}/"
          OUTPUT_FOLDER='${{ github.workspace }}/output/addons'
          cp --no-clobber '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE' "${ADDON_FOLDER}"
          mkdir -p "${OUTPUT_FOLDER}"
          cp "${ADDON_FOLDER}/" "${OUTPUT_FOLDER}"
      - name: Pack files into a .zip
        shell: bash
        run: |
          ADDON_NAME='romgerman.splasher'
          OUTPUT_NAME='splasher'
          ADDON_ZIP="${{ github.workspace }}/${OUTPUT_NAME}.zip"
          cd "${{ github.workspace }}/output"
          zip -r "${ADDON_ZIP}" 'addons/'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "splasher"
          path: ${{ github.workspace }}/splasher.zip
          retention-days: 30
  release:
    needs: pack
    name: Release addon
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "splasher"
          path: dist/
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
